---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.4

suites:
  - name: ports
    run_list:
      - recipe[chef-interview-questions::ports]
    attributes:
      apache:
        listen_ports: [81]
        default_site_port: 81
  - name: lamp
    run_list:
      - recipe[chef-interview-questions::lamp]
    attributes:
